WITH SONUC AS (
    SELECT SIP.ID,
           SIP.BELGE_NO,
           SIP.BELGE_TIPI,
           SIP.SIRA,
           SIP.CARI_KODU,
           SIP.TESLIM_CARI_KODU,
           SIP.TARIH,
           SIP.TESLIM_TARIHI,
           SIP.STOK_KODU,
           SIP.YAPKOD,
           SIP.MIKTAR,
           SIP.KALAN,
           SIP.TAMAMLANAN,
           SIP.DEPO_KODU,
           SIP.PROJE_KODU,
           SIP.EKALAN_NEDEN,
           SIP.EKALAN1,
           SIP.EKALAN2,
           SIP.KOSUL_KODU,
           SIP.PLASIYER_KODU,
           ISNULL(BAK.BAKIYE, 0) AS DEPO_BAKIYE
    FROM TF_VW_SIPARISDETAY AS SIP
    LEFT JOIN (
        SELECT SIPARIS_NO, SIPARIS_SIRA, SUM(MIKTAR - IRS_EDILEN) AS MIKTAR
        FROM TF_VW_PICSEVKEMRIDETAY
        GROUP BY SIPARIS_NO, SIPARIS_SIRA
    ) AS SEVK ON SEVK.SIPARIS_NO = SIP.BELGE_NO AND SEVK.SIPARIS_SIRA = SIP.SIRA
    LEFT JOIN TF_VW_STOKBAKIYE AS BAK 
      ON BAK.STOK_KODU = SIP.STOK_KODU AND ISNULL(BAK.YAPKOD, '') = ISNULL(SIP.YAPKOD, '') 
      AND BAK.DEPO_KODU = SIP.DEPO_KODU
    WHERE SIP.BELGE_TIPI = 'MS' 
      AND SIP.KAPALI = 'H' 
      AND SIP.KALAN - ISNULL(SEVK.MIKTAR, 0) > 0
      AND (@BASTAR IS NULL OR ISNULL(SIP.TESLIM_TARIHI, SIP.TARIH) >= @BASTAR)
      AND (@BITTAR IS NULL OR ISNULL(SIP.TESLIM_TARIHI, SIP.TARIH) <= @BITTAR)
      AND (@CARI_KODU IS NULL OR SIP.CARI_KODU LIKE '%' + @CARI_KODU)
      AND (@DEPO_KODU IS NULL OR SIP.DEPO_KODU = @DEPO_KODU)
      AND (@HAS_BALANCE = 0 OR ISNULL(BAK.BAKIYE, 0) > 0)
)

SELECT SIP.ID, SIP.BELGE_NO AS SIPARIS_NO, SIP.SIRA, SIP.CARI_KODU, CARI.CARI_ADI,
       SIP.TESLIM_CARI_KODU, CARI_TESLIM.CARI_ADI AS TESLIM_CARI_ADI,
       SIP.TARIH, SIP.TESLIM_TARIHI, SIP.STOK_KODU, 
       (CASE WHEN SIP.EKALAN_NEDEN = '1' AND SIP.EKALAN1 IS NOT NULL THEN SIP.EKALAN1 ELSE STOK.STOK_ADI END) AS STOK_ADI, 
       SIP.YAPKOD, YAP.YAPACIK, SIP.MIKTAR AS SIPARIS_MIKTAR,
       SIP.TAMAMLANAN AS GONDERILEN_MIKTAR, SIP.KALAN - ISNULL(SEVK.MIKTAR, 0) AS MIKTAR,
       SIP.DEPO_KODU, DEPO.DEPO_TANIMI, SIP.PROJE_KODU, SIP.EKALAN1, SIP.EKALAN2, SIP.DEPO_BAKIYE
FROM SONUC AS SIP
INNER JOIN TF_VW_SIPARIS AS MAS ON MAS.BELGE_NO = SIP.BELGE_NO AND MAS.BELGE_TIPI = SIP.BELGE_TIPI AND MAS.CARI_KODU = SIP.CARI_KODU
LEFT JOIN TF_VW_CARI AS CARI ON CARI.CARI_KODU = SIP.CARI_KODU
LEFT JOIN TF_VW_CARI AS CARI_TESLIM ON CARI_TESLIM.CARI_KODU = SIP.TESLIM_CARI_KODU
LEFT JOIN TF_VW_STOK AS STOK ON STOK.STOK_KODU = SIP.STOK_KODU
LEFT JOIN TF_VW_DEPO AS DEPO ON DEPO.DEPO_KODU = SIP.DEPO_KODU
LEFT JOIN TF_VW_YAPMAS AS YAP ON YAP.YAPKOD = SIP.YAPKOD
LEFT JOIN (
    SELECT SIPARIS_NO, SIPARIS_SIRA, SUM(MIKTAR - IRS_EDILEN) AS MIKTAR
    FROM TF_VW_PICSEVKEMRIDETAY
    GROUP BY SIPARIS_NO, SIPARIS_SIRA
) AS SEVK ON SEVK.SIPARIS_NO = SIP.BELGE_NO AND SEVK.SIPARIS_SIRA = SIP.SIRA
LEFT JOIN TF_VW_PLASIYER AS PL ON PL.PLASIYER_KODU = SIP.PLASIYER_KODU
ORDER BY ISNULL(SIP.TESLIM_TARIHI, SIP.TARIH), SIP.BELGE_NO, SIP.SIRA